apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
  name: prometheus-deployment
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector: 
    app: prometheus-server-25
  ports: 
    - name: prometheus 
      port: 8080
      targetPort: prometheus
      nodePort: 30001
  type: NodePort
